before_install:
   - wget https://s3.amazonaws.com/rebar3/rebar3
   - chmod u+x ./rebar3
install: "true"
language: erlang
sudo: false
otp_release:
  - 22.0
  - 21.0
script:
  - ./rebar3 as lint lint
  - ./rebar3 check
  - ./rebar3 as test coveralls send
